clang: Fix undefined reference to dladdr error
For some reason the cmake::find_library() can't detect the path to dl,
so we end up not including the right library when linking, hence the
error above.

Could be a hack/workaround the real problem.

Signed-off-by: Qais Yousef <qyousef@layalina.io>